# Build stage
FROM node:12 AS builder

COPY client /opt/app/client
COPY public /opt/app/public
COPY package.json /opt/app
COPY webpack.config.js /opt/app

WORKDIR /opt/app

RUN npm install
RUN npx webpack

# Final stage
FROM node:12-slim

WORKDIR /opt/app

# Copy only the built static files from the builder stage
COPY --from=builder /opt/app/public /opt/app/public

EXPOSE 8090

CMD cd public && npx node-static -p 8090 --host-address "0.0.0.0"
