apiVersion: apps/v1
kind: Deployment
metadata:
  name: notes-server
  labels:
    app: notes-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notes-server
  template:
    metadata:
      labels:
        app: notes-server
    spec:
      containers:
      - name: notes-server
        image: mpelekh/notes-server:latest
        ports:
        - containerPort: 3000
        env:
        - name: MONGODB_URI
          value: "mongodb://mongodb-service:27017/notes"
        resources:
          requests:
            memory: "128Mi"
            cpu: "200m"
          limits:
            memory: "256Mi"
            cpu: "500m" 
 